package lession10;

import java.io.IOException;

/**
 * 作业类型：代码纠错
 * 作业内容：另行参考作业描述！
 * 
 * @author banma
 */
public class Main_1_5 {

	public static void main(String[] args) {
		// 16行为什么会报错，明明已经try 起来了 。如何解决？
		try {
			test();
		} catch (ArrayIndexOutOfBoundsException e) {
			// TODO: handle exception
		}
		
	}
	
	public static void test()throws IOException,NullPointerException {

	}

}
